#!/bin/bash
#
# The objective of this script is to generate a list of file paths and their corresponding hashes, from
# the website. This can help in easily creating the list of files.
#
# It is meant to be run independently, regardless of PscgBuildOS, and can be used to generate a copy-pastable list of files and hashes.
# Its output, can be used to generate pscg_alpineos.minirootfs_upstream.buildconfig - which would then not need
# to access the internet to fetch th files, and allow offline builds.
#
# As this script is useful, it is kept in the tools directory, and added to the source control.
# On the other hand, as it not meant to be run as a part of the build system, it is kept without the logs etc.
#

ALPINEOS_MINI_ROOTFS_ARCHS=(aarch64 armhf armv7 loongarch64 ppc64le riscv64 s390x x86 x86_64)
: ${ALPINEOS_VERSION_SERIES=3.22}
: ${ALPINEOS_VERSION=3.22.1}

declare -A ALPINEOS_MINI_ROOTFS_ARRAY # note that you cannot export ARRAY - but there are tricks to do that if absolutely necessary. As the resulting code is expected to be sourced directly from the using script, that is fine. If that changes, you need to be aware of this line

# Path to buildconfig file
generate_mini_rootfs_buildconfig() {
	local arch=$1
	local tarball=${ALPINEOS_MINI_ROOTFS_ARRAY["${arch}_tarball"]}
	local sha256=${ALPINEOS_MINI_ROOTFS_ARRAY["${arch}_sha256"]}

	echo "tarball_${arch}=\"$tarball\""
	echo "sha256_${arch}=\"$sha256\""
}

main() {
	set -euo pipefail
	local base_url digest_url digest
	for arch in "${ALPINEOS_MINI_ROOTFS_ARCHS[@]}"; do
		base_url=https://dl-cdn.alpinelinux.org/alpine/v${ALPINEOS_VERSION_SERIES}/releases/${arch}/alpine-minirootfs-${ALPINEOS_VERSION}-${arch}.tar.gz
		ALPINEOS_MINI_ROOTFS_ARRAY["${arch}_tarball"]="$base_url"
		digest_url="${base_url}.sha256"

		echo "Fetching ${arch} tarball and sha256..."
		digest=$(curl --fail-with-body $digest_url 2>/dev/null | cut -d ' ' -f 1) # --fail-with-body ensures that if the file is not found, it will return an error
		echo "Digest for ${arch}: $digest"
		ALPINEOS_MINI_ROOTFS_ARRAY["${arch}_sha256"]="$digest"
	done

	echo "Generated configuration:"

	if [ $# -gt 0 ] ; then
		echo "Generating buildconfig at $1. If you override your previous buildconfig, it is your problem."
	fi

	echo -e "# autogenerated by $(basename $0)\n" > "${1:-/dev/stdout}"
	echo "ALPINEOS_MINI_ROOTFS_ARCHS=(aarch64 armhf armv7 loongarch64 ppc64le riscv64 s390x x86 x86_64)
: \${ALPINEOS_VERSION_SERIES=3.22}
: \${ALPINEOS_VERSION=3.22.1}
declare -A ALPINEOS_MINI_ROOTFS_ARRAY
" >> ${1:-/dev/stdout}


	for arch in $(printf "%s\n" "${ALPINEOS_MINI_ROOTFS_ARCHS[@]}" | sort); do
		echo "ALPINEOS_MINI_ROOTFS_ARRAY["${arch}_tarball"]=${ALPINEOS_MINI_ROOTFS_ARRAY["${arch}_tarball"]}" >> "${1:-/dev/stdout}"
		echo "ALPINEOS_MINI_ROOTFS_ARRAY["${arch}_sha256"]=${ALPINEOS_MINI_ROOTFS_ARRAY["${arch}_sha256"]}" >> "${1:-/dev/stdout}"
	done

}

main $@