LABEL PscBuildOS-emmc
  LINUX /Image.gz
  FDT /dtb/amlogic/meson-gxl-s905w-p281.dtb
  INITRD /initramfs.cpio
  APPEND overlayfs systemd.debug_shell=ttyAML0 console=ttyAML0,115200n8 earlycon=meson,0xc81004c0  pscgrd.hw.bsp=amlogic  cpufreq.default_governor=ondemand emmc_device=mmcblk1 removablemedia_device=mmcblk0 bootfrom=emmc pscgrd.debug.openvts=all pscgrd.net.autotelnet=true

