# Please excuse the long lines - setting the device paths from the bootloader can save some detection code, although it is unnecessary
LABEL PscgBuildOS-removablemedia
  LINUX /Image.gz
  FDT /dtb/amlogic/meson-gxl-s905w-p281.dtb
  INITRD /initramfs.cpio
  APPEND overlayfs systemd.debug_shell=ttyAML0 console=tty0 console=ttyAML0,115200n8 waitforremovablemedia installer_a_only=true nokaslr earlycon=meson,0xc81004c0  pscgrd.hw.bsp=amlogic  cpufreq.default_governor=ondemand emmc_device=mmcblk1 removablemedia_device=mmcblk0 bootfrom=removablemedia pscgrd.debug.openvts=all pscgrd.net.autotelnet=true